# Generated by Django 3.0.4 on 2020-03-11 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_lent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 21, 52, 22, 442769)),
        ),
    ]
