# Generated by Django 3.0.4 on 2020-03-12 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200311_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 3, 10, 21, 545184), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 3, 10, 21, 545263)),
        ),
    ]
