# Generated by Django 3.0.4 on 2020-03-12 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200312_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 3, 18, 1, 582565), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 3, 18, 1, 582661)),
        ),
    ]
