# Generated by Django 3.0.4 on 2020-03-17 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200315_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_expired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 11, 46, 27, 369346), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 11, 46, 27, 369411)),
        ),
    ]
